# Generated by Django 4.1.7 on 2023-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
