# Generated by Django 4.1.7 on 2023-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
