# Generated by Django 4.1.7 on 2023-03-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_post_type_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('psot_change_post', 'Can change post'), ('post_delete_post', 'Can delete post')]},
        ),
    ]
