# Generated by Django 4.1.7 on 2023-03-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_options_alter_photos_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(default='', upload_to='post_images'),
        ),
    ]
