# Generated by Django 4.1.7 on 2023-03-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_images'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photos',
            unique_together=set(),
        ),
    ]
