# Generated by Django 4.1.7 on 2023-03-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_photos_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='contact_info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
