# Generated by Django 4.1.7 on 2023-03-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_images_post_contact_info'),
        ('favorite_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='post',
        ),
        migrations.CreateModel(
            name='FavoriteListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favorite_list.favoritelist')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
