# Generated by Django 4.1.7 on 2023-03-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_images_post_contact_info'),
        ('favorite_list', '0002_remove_favoritelist_post_favoritelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelist',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.DeleteModel(
            name='FavoriteListItem',
        ),
    ]
