# Generated by Django 4.1.7 on 2023-04-16 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_notifications_notification_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_to',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
