# Generated by Django 4.1.7 on 2023-04-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notification_to_notifications_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel('Notifications'),
    ]
