# Generated by Django 4.1.7 on 2023-04-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='target_content_type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='target',
            field=models.CharField(max_length=255,null=False, default='default_target'),
        ),
    ]
