# Generated by Django 4.1.7 on 2023-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notifications_target_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='actor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient',
            field=models.PositiveIntegerField(),
        ),
    ]
