# Generated by Django 4.1.7 on 2023-04-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notifications_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='verb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
