# Generated by Django 4.1.7 on 2023-04-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notifications_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='target',
            field=models.CharField(max_length=255),
        ),
    ]
